# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'map_app.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.map_label = QtWidgets.QLabel(self.centralwidget)
        self.map_label.setGeometry(QtCore.QRect(75, 0, 650, 450))
        self.map_label.setCursor(QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.map_label.setText("")
        self.map_label.setObjectName("map_label")
        self.map_type_btn = QtWidgets.QPushButton(self.centralwidget)
        self.map_type_btn.setGeometry(QtCore.QRect(10, 520, 150, 50))
        font = QtGui.QFont()
        font.setFamily("STZhongsong")
        font.setPointSize(22)
        self.map_type_btn.setFont(font)
        self.map_type_btn.setObjectName("map_type_btn")
        self.search_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.search_lineEdit.setGeometry(QtCore.QRect(10, 455, 300, 40))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.search_lineEdit.setFont(font)
        self.search_lineEdit.setText("")
        self.search_lineEdit.setObjectName("search_lineEdit")
        self.search_btn = QtWidgets.QPushButton(self.centralwidget)
        self.search_btn.setGeometry(QtCore.QRect(310, 455, 75, 40))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semilight")
        font.setPointSize(15)
        self.search_btn.setFont(font)
        self.search_btn.setObjectName("search_btn")
        self.reset_btn = QtWidgets.QPushButton(self.centralwidget)
        self.reset_btn.setGeometry(QtCore.QRect(210, 520, 171, 50))
        font = QtGui.QFont()
        font.setFamily("STZhongsong")
        font.setPointSize(19)
        self.reset_btn.setFont(font)
        self.reset_btn.setObjectName("reset_btn")
        self.address_textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.address_textBrowser.setGeometry(QtCore.QRect(420, 455, 256, 115))
        self.address_textBrowser.setObjectName("address_textBrowser")
        self.index_checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.index_checkBox.setGeometry(QtCore.QRect(680, 470, 111, 17))
        self.index_checkBox.setChecked(True)
        self.index_checkBox.setObjectName("index_checkBox")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Map"))
        self.map_type_btn.setText(_translate("MainWindow", "Схема"))
        self.search_btn.setText(_translate("MainWindow", "Искать"))
        self.reset_btn.setText(_translate("MainWindow", "Сброс"))
        self.index_checkBox.setText(_translate("MainWindow", "Почтовый индекс"))
